---
- name: "NameSilo API"
  namesilo_dns:
    apikey: '{{ role_namesilo_apikey }}'
    domain: '{{ item.domain }}'
    type: '{{ item.type }}'
    host: '{{ item.host }}'
    value: '{{ item.value }}'
    ttl: '{{ item.ttl | default(omit) }}'
    distance: '{{ item.distance | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
  delegate_to: 'localhost'
  loop: '{{ role_namesilo_data }}'
  ignore_errors: true
...
